apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: retail-store-cart
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - app: cart
            syncWave: "1"
  template:
    metadata:
      name: 'retail-store-{{.app}}'
      annotations:
        argocd.argoproj.io/sync-wave: '{{.syncWave}}'
    spec:
      project: retail-store
      source:
        repoURL: https://github.com/LondheShubham153/retail-store-sample-app
        targetRevision: main
        path: 'src/{{.app}}/chart'
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: retail-store
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
